version: 2.1

orbs:
  altostra-orb: altostra/altostra-orb@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  integration-test-setup:
    docker:
      - image: cimg/node:12.19
    steps:
      - altostra-orb/setup

  integration-test-deploy_no_name:
    docker:
      - image: cimg/node:12.19
    working_directory: ~/altostra-orb_1/resources/test_project
    steps:
      - checkout:
          path: ~/altostra-orb_1
      - altostra-orb/setup
      - altostra-orb/deploy:
          instance-name: "circleci"
          env-name: "Daylong"

  integration-test-deploy_with_name:
    docker:
      - image: cimg/node:12.19
    working_directory: ~/altostra-orb_2/resources/test_project
    steps:
      - checkout:
          path: ~/altostra-orb_2
      - altostra-orb/setup
      - altostra-orb/deploy:
          instance-name: "circleci1"
          env-name: "Daylong"
          image-name: "$CIRCLE_BUILD_NUM"

  integration-test-push_deploy:
    docker:
      - image: cimg/node:12.19
    working_directory: ~/altostra-orb_3/resources/test_project
    steps:
      - checkout:
          path: ~/altostra-orb_3
      - altostra-orb/setup
      - altostra-orb/push:
          image-name: "$CIRCLE_BUILD_NUM"
      - altostra-orb/deploy-version:
          instance-name: "circleci2"
          env-name: "Daylong"
          image-name: "$CIRCLE_BUILD_NUM"


workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source

      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: altostra/altostra-orb
          context: orb-publishing # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires: [hold-for-dev-publish]
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Run any integration tests defined within the `jobs` key.
      - integration-test-setup
      - integration-test-deploy_no_name
      - integration-test-deploy_with_name
      - integration-test-push_deploy

      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: altostra/altostra-orb
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-setup
            - integration-test-deploy_no_name
            - integration-test-deploy_with_name
            - integration-test-push_deploy
          filters:
            branches:
              only:
                - master
                - main
